name: Build and Release

on:
  workflow_dispatch:
    inputs:
      versionBumpLevel:
        description: 'Version bump level (patch, minor, major)'
        required: true
        type: choice
        default: 'patch'
        options:
        - patch
        - minor
        - major
        - none

jobs:
  build-and-release:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up XCode 
        run: sudo xcode-select --switch /Applications/Xcode_14.1.app

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Set up Cocoapods
        run: gem install cocoapods

      - name: Bump version
        run: ruby ./scripts/bump_pod_version.rb ${{ github.event.inputs.versionBumpLevel }}

      - name: Build XCFramework
        run: ./scripts/build_framework.sh

      - name: Get new version
        id: version
        run: echo "VERSION=$(ruby -e 'puts File.read("./OSBarcodeLib.podspec").match(/spec.version.*=.*\"(\d+\.\d+\.\d+)\"/)[1]')" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          draft: false
          prerelease: false
          files: 'scripts/build/OSBarcodeLib.zip'

      - name: Deploy to Cocoapods
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: pod trunk push ./OSBarcodeLib.podspec --allow-warnings
      
      - name: Commit changes
        if: ${{ github.event.inputs.versionBumpLevel != 'none' }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "chore: Bump version to ${{ env.VERSION }}"
          git pull --rebase
          git push origin HEAD:main
